"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class GetPage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PAGE_FIELD_NUMBER: builtins.int
    page: typing.Text = ...
    def __init__(self,
        *,
        page : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"page",b"page"]) -> None: ...
global___GetPage = GetPage

class ButtonInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    ICON_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    label: typing.Text = ...
    type: typing.Text = ...
    icon: typing.Text = ...
    def __init__(self,
        *,
        name : typing.Text = ...,
        label : typing.Text = ...,
        type : typing.Text = ...,
        icon : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"icon",b"icon",u"label",b"label",u"name",b"name",u"type",b"type"]) -> None: ...
global___ButtonInfo = ButtonInfo
