# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamberry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streamberry.proto',
  package='gen.proto.streamberry',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11streamberry.proto\x12\x15gen.proto.streamberry\"\x17\n\x07GetPage\x12\x0c\n\x04page\x18\x01 \x01(\t\"U\n\nButtonInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04icon\x18\x04 \x01(\t\x12\x0e\n\x06params\x18\x05 \x01(\t\"F\n\rButtonClicked\x12\x35\n\nbuttonInfo\x18\x01 \x01(\x0b\x32!.gen.proto.streamberry.ButtonInfo\"\n\n\x08\x43lickAckb\x06proto3'
)




_GETPAGE = _descriptor.Descriptor(
  name='GetPage',
  full_name='gen.proto.streamberry.GetPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='gen.proto.streamberry.GetPage.page', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=67,
)


_BUTTONINFO = _descriptor.Descriptor(
  name='ButtonInfo',
  full_name='gen.proto.streamberry.ButtonInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gen.proto.streamberry.ButtonInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='gen.proto.streamberry.ButtonInfo.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='gen.proto.streamberry.ButtonInfo.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon', full_name='gen.proto.streamberry.ButtonInfo.icon', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='gen.proto.streamberry.ButtonInfo.params', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=154,
)


_BUTTONCLICKED = _descriptor.Descriptor(
  name='ButtonClicked',
  full_name='gen.proto.streamberry.ButtonClicked',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buttonInfo', full_name='gen.proto.streamberry.ButtonClicked.buttonInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=226,
)


_CLICKACK = _descriptor.Descriptor(
  name='ClickAck',
  full_name='gen.proto.streamberry.ClickAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=238,
)

_BUTTONCLICKED.fields_by_name['buttonInfo'].message_type = _BUTTONINFO
DESCRIPTOR.message_types_by_name['GetPage'] = _GETPAGE
DESCRIPTOR.message_types_by_name['ButtonInfo'] = _BUTTONINFO
DESCRIPTOR.message_types_by_name['ButtonClicked'] = _BUTTONCLICKED
DESCRIPTOR.message_types_by_name['ClickAck'] = _CLICKACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPage = _reflection.GeneratedProtocolMessageType('GetPage', (_message.Message,), {
  'DESCRIPTOR' : _GETPAGE,
  '__module__' : 'streamberry_pb2'
  # @@protoc_insertion_point(class_scope:gen.proto.streamberry.GetPage)
  })
_sym_db.RegisterMessage(GetPage)

ButtonInfo = _reflection.GeneratedProtocolMessageType('ButtonInfo', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONINFO,
  '__module__' : 'streamberry_pb2'
  # @@protoc_insertion_point(class_scope:gen.proto.streamberry.ButtonInfo)
  })
_sym_db.RegisterMessage(ButtonInfo)

ButtonClicked = _reflection.GeneratedProtocolMessageType('ButtonClicked', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONCLICKED,
  '__module__' : 'streamberry_pb2'
  # @@protoc_insertion_point(class_scope:gen.proto.streamberry.ButtonClicked)
  })
_sym_db.RegisterMessage(ButtonClicked)

ClickAck = _reflection.GeneratedProtocolMessageType('ClickAck', (_message.Message,), {
  'DESCRIPTOR' : _CLICKACK,
  '__module__' : 'streamberry_pb2'
  # @@protoc_insertion_point(class_scope:gen.proto.streamberry.ClickAck)
  })
_sym_db.RegisterMessage(ClickAck)


# @@protoc_insertion_point(module_scope)
