# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamberry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streamberry.proto',
  package='gen.proto.streamberry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11streamberry.proto\x12\x15gen.proto.streamberry\"\t\n\x07GetPageb\x06proto3')
)




_GETPAGE = _descriptor.Descriptor(
  name='GetPage',
  full_name='gen.proto.streamberry.GetPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['GetPage'] = _GETPAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPage = _reflection.GeneratedProtocolMessageType('GetPage', (_message.Message,), dict(
  DESCRIPTOR = _GETPAGE,
  __module__ = 'streamberry_pb2'
  # @@protoc_insertion_point(class_scope:gen.proto.streamberry.GetPage)
  ))
_sym_db.RegisterMessage(GetPage)


# @@protoc_insertion_point(module_scope)
