"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Ping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PING_MESSAGE_FIELD_NUMBER: builtins.int
    ping_message: typing.Text = ...
    def __init__(self,
        *,
        ping_message : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ping_message",b"ping_message"]) -> None: ...
global___Ping = Ping

class Pong(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PONG_MESSAGE_FIELD_NUMBER: builtins.int
    pong_message: typing.Text = ...
    def __init__(self,
        *,
        pong_message : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"pong_message",b"pong_message"]) -> None: ...
global___Pong = Pong
